install

carpetas <- read_csv('./data/carpetas-de-investigacion-pgj-de-la-ciudad-de-mexico.csv')
victimas <- read_csv('./data/victimas-en-carpetas-de-investigacion-pgj.csv')

str(carpetas)

head(carpetas)
head(victimas)

colnames(carpetas)
colnames(victimas)

unique(carpetas$delito)
unique(victimas$Delito)

prueba <- victimas %>% filter(Delito == "ROBO A PASAJERO A BORDO DE TRANSPORTE PÚBLICO CON VIOLENCIA")

# "ROBO A PASAJERO A BORDO DE TRANSPORTE PÚBLICO CON VIOLENCIA"
# "ROBO A PASAJERO A BORDO DE TRANSPORTE PÚBLICO SIN VIOLENCIA" 

# "ROBO A PASAJERO A BORDO DE METROBUS CON VIOLENCIA"
# "ROBO A PASAJERO A BORDO DE METROBUS SIN VIOLENCIA"

# "ROBO A PASAJERO A BORDO DE METRO SIN VIOLENCIA"
# "ROBO A PASAJERO A BORDO DE METRO CON VIOLENCIA"

# "ROBO A PASAJERO EN ECOBUS SIN VIOLENCIA"
# "ROBO A PASAJERO EN ECOBUS CON VIOLENCIA" 

# "ROBO A PASAJERO EN TROLEBUS SIN VIOLENCIA"
# "ROBO A PASAJERO EN TROLEBUS CON VIOLENCIA"

# "ROBO A PASAJERO EN TREN LIGERO SIN VIOLENCIA"
# "ROBO A PASAJERO EN TREN LIGERO CON VIOLENCIA"

# "ROBO A PASAJERO EN TREN SUBURBANO SIN VIOLENCIA"
# "ROBO A PASAJERO EN TREN SUBURBANO CON VIOLENCIA" 

# "ROBO A PASAJERO EN RTP CON VIOLENCIA"
# "ROBO A PASAJERO EN RTP SIN VIOLENCIA"  

# "ROBO A TRANSEUNTE A BORDO DE TAXI PÚBLICO Y PRIVADO CON VIOLENCIA"
# "ROBO A TRANSEUNTE A BORDO DE TAXI PUBLICO Y PRIVADO SIN VIOLENCIA"

# "ROBO A PASAJERO A BORDO DE PESERO Y VEHICULO CON VIOLENCIA" 
# "ROBO A PASAJERO A BORDO DE PESERO Y VEHICULO CON VIOLENCIA" 
